version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db-admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka-s:
    depends_on:
      - db
    image: dodeeric/omeka-s:latest 
    restart: always
    ports:
      - "80:80"
